### ISSUE TITLE
Proposal: Add tests to Anosql

### ISSUE THREAD

**Issue by alecbrooks** [honza/anosql#11]
I'd like to make Anosql easier to develop by adding unit tests. I'm writing this as a proposal to verify that you'd have the time and interest in merging these.

I'm thinking the pull requests would look something like:
- [x] Add Holgers Peter's unit tests from pull request #3 .
- [x] Add analogous tests for Postgres using testing.postgresql.
- [x] Add his tox tests, also from pull request #3.

Once these pull requests are finished, maybe the next issue is removing the "very alpha" warning? 😺

**Comment by honza** [comment]
Let's do this :sparkles:

**Comment by honza** [comment]
@alecbrooks How would you like to take a stab at the postgresql testing? :)

**Comment by alecbrooks** [comment]
Sure! I might not have time for a week or so.
