### ISSUE TITLE
Upcoming deprecation of wheel package for psycopg2

### ISSUE THREAD

**Issue by alecbrooks** [honza/anosql#19]
I looked through the TravisCI logs and noticed the following warning:

>UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

**Comment by nackjicholson** [comment]
@alecbrooks Is it clear to you what actually needs to be done about this?

**Comment by alecbrooks** [comment]
I think we just need to update test_requirements.txt to say "psycopg2-binary" instead of "psycopg2". The page in the psycopg2 docs says packages shouldn't depend on the binary package, but I don't think that applies here because test_requirements.txt is only used for testing.

**Comment by alecbrooks** [comment]
This isn't an issue anymore after  @nackjicholson updated tests (see commit https://github.com/honza/anosql/commit/ca2137d8e2db04984176d7cfa628561dc3356e1f).
