### ISSUE TITLE
Questions: How does the `!` and `<!` stuff for names work?

### ISSUE THREAD

**Issue by nackjicholson** [honza/anosql#21]
I was looking at the `anosql` source and noticed the lines which choose the `sql_type`. I don't think I really understand that part. Could you provide an example of how the value after `-- name:` impacts how the sql gets executed and the results returned?

Another question. Is it possible (or okay) to execute sql with anosql which contains multiple statements separated by `;`.

**Comment by nackjicholson** [comment]
Thanks for the help. 😒

**Comment by honza** [comment]
Is that a sad face? Why? Are you unhappy with my solution to your problem?

**Comment by nackjicholson** [comment]
Oh, sorry was confused. I thought you just closed the issue without response. I was asking a question and expecting you to respond with answers to those questions. I now see that you made commits to address my questions. I will look into those commits to see what the capabilities of anosql now are.

👍 😄
