### ISSUE TITLE
keyError at insert_returning fuction

### ISSUE THREAD

**Issue by johnmba** [honza/anosql#51]
I love the concept of anosql but i think there is an issue with insert_returning function. 

- i changed my pscopg2 connection cursor to dict and whenever i execute an insert  returning sql it gives this error  below:
> user = db._model.in_acc(
  File &quot;/home/johnmba/.local/share/virtualenvs/Account-aQwD5Z7L/lib/python3.9/site-packages/anosql/core.py&quot;, line 168, in fn
    return driver_adapter.insert_returning(conn, query_name, sql, parameters)
  File &quot;/home/johnmba/.local/share/virtualenvs/Account-aQwD5Z7L/lib/python3.9/site-packages/anosql/adapters/psycopg2.py&quot;, line 55, in insert_returning
    return res[0] if len(res) == 1 else res
KeyError: 0

- tried looking into the package and tried returning just res.fetchone it worked but returned  this below:
>  RealDictRow([('extid', '31681bd1-4539-44f2-b4fd-d469f54b4500')])

- the inserted record is not found in database

**Comment by johnmba** [comment]
@johnmba 
- i just realize that inserts don't work with dict cursor but the default cursor
- but successfully  inserted data doesn't reflect in the database

**Comment by honza** [comment]
Please note that as the README suggests, this project is deprecated in favour of [aiosql](https://github.com/nackjicholson/aiosql).
