### ISSUE TITLE
The '?' sqlite special char is not taken into account

### ISSUE THREAD

**Issue by garaud** [honza/anosql#6]
Hi,

When you have a query such as:
```sql
SELECT *
FROM table_name
WHERE name = %s
```
and you use sqlite (the `%s` is replaced by a '?'), Then, a mere `queries.foo(cnx, 'John')` raises a  `ProgrammingError Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.`

Damien G.

**Comment by honza** [comment]
Thank you!
